version: "3.8"
services:
  webserver:
    restart: always
    ports:
      - 80:80
    image: nginx:stable-alpine
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src:/var/www/src

  db:
    restart: always
    ports:
      - 5432:5432
    image: postgres:13.13-alpine3.19
    environment:
      POSTGRES_DATABASE: cosmobot_db
      POSTGRES_USER: raptor
      POSTGRES_PASSWORD: lama22
      POSTGRES_ROOT_PASSWORD: lama22
    volumes:
      - .:/docker-entrypoint-initdb.d
      - dbdata:/var/lib/postgresql/data
    
  app:
    build:
      context: docker
      dockerfile: app.Dockerfile
    env_file:
      - config/xdebug.env
    volumes:
      - ./src:/var/www/src
      - ./config/php.ini:/usr/local/etc/php/php.ini:ro
    depends_on:
      - db
      - webserver

  composer:
    build:
      context: docker
      dockerfile: composer.Dockerfile
    volumes:
      - ./src:/var/www/src
    depends_on:
      - app

  localxpose:
    image: localxpose/localxpose:latest
    restart: unless-stopped
    command: tunnel -r http --to bot:5000
    environment:
      ACCESS_TOKEN: GMz8SkPJXg9PG8HRykQED9cOTLUc5tBrTx9BgRxs

  bot:
    restart: always
    ports:
      - "5000:5000"
    build:
      context: docker
      dockerfile: bot.Dockerfile
    environment:
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=True
      - CONN_STR=mongodb://user:pass@mongodb
    volumes:
      - ./bot:/var/www/bot
    command: python main.py
  #    networks:
  #      - bridge

  mongodb:
    image: mongo:4.2.6-bionic
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=chains
      - MONGO_INITDB_ROOT_USERNAME=raptor
      - MONGO_INITDB_ROOT_PASSWORD=lama22
    volumes:
      - ./db-data/mongo/:/data/mongo
#    networks:
#      - web_db_mongo

#networks:
#  web_db_mongo:
#    external:
#      name: docker_database_web
#  bridge:
#    driver: bridge
#    ipam:
#      driver: default
#      config:
#      - subnet: 0.0.0.0/24
#        gateway: 0.0.0.0

volumes:
  dbdata:
    driver: local
